apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::156470783903:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8GL7774O246L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::156470783903:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-17T07:54:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1470"
  uid: c7477a00-9c41-4da4-9795-5612f50147e5
